name: Deploy Portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER_HOST }}
          port: 2222
          username: ${{ secrets.SERVER_USER }}
          protocol: sftp
          security: ssh-key
          key: ${{ secrets.DEPLOY_KEY }}
          local-dir: ./dist/
          server-dir: /home/${{ secrets.SERVER_USER }}/web/glen.cx/public_html/
          dangerous-clean-slate: true
