name: Deploy Portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER_HOST }}
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}
          port: 2222
          local_path: './dist/*'
          remote_path: /home/${{ secrets.SERVER_USER }}/web/glen.cx/public_html/
          sftp_only: true
